### PR TITLE
feat: make chapters accessable via GraphQL

### LINKED ISSUE #100: GraphQL: can't query chapter
Steps: 
* clean install
* import 'fanboys.fm'

query 
```
{ episode (id:1
) {
  id
  title
  chapters {
    image
    link
    start
    title
  }
} 
 }
```

## Actual Result :
crash
```
[error] #PID<0.3292.0> running RadiatorWeb.Endpoint (connection #PID<0.3283.0>, stream id 2) terminated
Server: localhost:4000 (http)
Request: POST /api/graphiql
** (exit) an exception was raised:
    ** (RuntimeError) Valid association chapters not found on schema Radiator.Directory.Episode
Got: nil

        (dataloader) lib/dataloader/ecto.ex:399: Dataloader.Source.Dataloader.Ecto.chase_down_queryable/2
        (dataloader) lib/dataloader/ecto.ex:422: Dataloader.Source.Dataloader.Ecto.get_keys/2
        (dataloader) lib/dataloader/ecto.ex:327: Dataloader.Source.Dataloader.Ecto.fetch/3
        (dataloader) lib/dataloader/ecto.ex:367: Dataloader.Source.Dataloader.Ecto.load/3
        (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
        (dataloader) lib/dataloader.ex:128: Dataloader.load_many/4
        (absinthe) lib/absinthe/resolution/helpers.ex:255: Absinthe.Resolution.Helpers.do_dataloader/6
        (absinthe) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:209: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:168: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:153: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:72: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:257: Absinthe.Phase.Document.Execution.Resolution.build_result/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:153: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:72: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:53: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:24: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
        (absinthe) lib/absinthe/pipeline.ex:274: Absinthe.Pipeline.run_phase/3
        (absinthe_plug) lib/absinthe/plug.ex:421: Absinthe.Plug.run_query/4
        (absinthe_plug) lib/absinthe/plug.ex:247: Absinthe.Plug.call/2

```

## Expected Result
should show chapters or empty list

Without chapters in the query, this is returned:
```
{
  "data": {
    "episode": {
      "id": "1",
      "title": "Episode #369 - Bifi Roll Inside-Out"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by eteubert**
Chapters are nested under `episode { audio { chapters { ... }}}` now. I considered adding it directly under `episode` and hide the internal structure -- however there are cases where an audio exists without the episode parent so chapters _must_ be accessible through the audio in any case.

fixes #100

### CODE REVIEW

**Comment by monkeydom** [comment]
Compiling 101 files (.ex)
```
warning: unused alias AudioMeta
  lib/radiator_web/graphql/public/resolvers/directory.ex:4
```

**Comment by monkeydom** [comment]
querying from podcasts through to chapters throws an adudio not loaded exception: 
```graphql
query { publishedPodcast (id:3
) {
  id
  episodes {
    id
    title
    audio {
      chapters {
        image
        link
        start
        title
      }
    }
  }
} }
```

```elixir
[error] #PID<0.1341.0> running RadiatorWeb.Endpoint (connection #PID<0.1340.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: POST /api/graphiql
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in RadiatorWeb.GraphQL.Admin.Resolvers.Editor.get_chapters/3
        (radiator) lib/radiator_web/graphql/admin/resolvers/editor.ex:283: RadiatorWeb.GraphQL.Admin.Resolvers.Editor.get_chapters(#Ecto.Association.NotLoaded<association :audio is not loaded>, %{order: :asc}, #Absinthe.Resolution<[acc: %{Absinthe.Middleware.Async => false, Absinthe.Middleware.Batch => %{input: [], output: %{}}}, adapter: Absinthe.Adapter.LanguageConventions, arguments: %{order: :asc}, context: %{__absinthe_plug__: %{uploads: %{}}, loader: %Dataloader{options: [get_policy: :raise_on_error], sources: %{Radiator.AudioMeta => %Dataloader.Ecto{batches: %{}, default_params: %{}, options: [], query: #Function<2.59898058/2 in Radiator.AudioMeta.data/0>, repo: Radiator.Repo, repo_opts: [], results: %{}, run_batch: #Function<3.24511035/5 in Dataloader.Ecto.new/2>}, Radiator.Directory => %Dataloader.Ecto{batches: %{}, default_params: %{}, options: [], query: #Function<0.20725220/2
```

**Comment by monkeydom** [comment]
Just going through an Episode works as expected 👍 
```graphql
query { publishedEpisode (id:248
) {
  id
  audio {
    id
    chapters {
      image
      link
      start
      title
    }
  } 
} }
```

```json
{
  "data": {
    "publishedEpisode": {
      "audio": {
        "chapters": [
          {
            "image": null,
            "link": "https://blog.regehr.org/archives/1653",
            "start": 0,
            "title": "ASCII-art code comments"
          },
          {
            "image": null,
            "link": "https://www.ifixit.com/Teardown/MacBook+Pro+15-Inch+Touch+Bar+2019+Teardown/123653#s239249",
            "start": 126500,
            "title": "2019 butterfly teardown"
          },
          {
            "image": null,
            "link": "https://twitter.com/_inside/status/1133051998763409409",
            "start": 435000,
            "title": "Watch independence?"
          },
          {
            "image": null,
            "link": "https://www.bloomberg.com/news/audio/2019-05-28/wwdc-preview-with-apple-s-former-app-approval-chief-podcast",
            "start": 765500,
            "title": "Shoemaker interview"
          },
          {
            "image": null,
            "link": null,
            "start": 863000,
            "title": "Read-only system partition"
          },
          {
            "image": null,
            "link": "https://mobelux.com/",
            "start": 1258000,
            "title": "Sponsor: Mobelux"
          },
          {
            "image": null,
            "link": null,
            "start": 1337000,
            "title": "New iPod Touch?!"
          },
          {
            "image": "http://darthdom.local:9000/radiator/chapter/3215/Chapter_8_original.png?v=63727052613",
            "link": "https://9to5mac.com/2019/05/28/ios-13-screenshots-dark-mode-more/",
            "start": 1842000,
            "title": "Leaked screenshots"
          },
          {
            "image": null,
            "link": "http://jamf.com/atp",
            "start": 2913000,
            "title": "Sponsor: Jamf Now"
          },
          {
            "image": null,
            "link": null,
            "start": 2969833,
            "title": "Pro Display rumors"
          },
          {
            "image": null,
            "link": null,
            "start": 3360500,
            "title": "Final Mac Pro predictions"
          },
          {
            "image": null,
            "link": "https://expressvpn.com/atp",
            "start": 5107874,
            "title": "Sponsor: ExpressVPN"
          },
          {
            "image": null,
            "link": null,
            "start": 5206250,
            "title": "What won't be mentioned?"
          },
          {
            "image": null,
            "link": null,
            "start": 6122500,
            "title": "Presenting Marzipan"
          },
          {
            "image": null,
            "link": "http://jonathanmann.net/",
            "start": 6737500,
            "title": "Ending theme"
          },
          {
            "image": null,
            "link": null,
            "start": 6799874,
            "title": "10-year computers"
          }
        ],
        "id": "248"
      },
      "id": "248"
    }
  }
}
```

**Comment by monkeydom** [comment]
Generally speaking I don't know if we eventually want to diverge in the published interface from the admin one. I think this is good for now, but the published interface should mirror more the rss style and names, vs. the admin interface should have our own structure.

**Comment by monkeydom** [comment]
also `setChapters` seems a little bit of a very strong hammer. We'll probably need a more refined interface to update chapter entries. But it seems to work with an escaped PSC stream at least. Probably needs some follow up issues for:
* chapter images - didn't test if they upload here, and if so, the old ones need to be deleted from the bucket
* finer manipulation api

**Comment by eteubert** [comment]
Agree with the fine grained chapter API, it's part of #101 

Gut feeling says it's a good idea to lean the public api on feed structure rather than our internal one. Opened #114

**Pull request merged**
